POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo evento 22",
    "details": "Null",
    "maximumAttendees": 1
}


###

POST http://localhost:3333/events/97f5231b-66c1-4452-af95-9761dc4496e3/attendees
Content-Type: application/json

{
    "name": "Gabriel Rodrigues Leão",
    "email": "gabrielrleao@hotmail.com"
}

###

GET http://localhost:3333/events/97f5231b-66c1-4452-af95-9761dc4496e3

###

GET http://localhost:3333/attendees/1/badge